### ISSUE TITLE
unable to find version `1.1.0`

### ISSUE THREAD

**Issue by cyberblack28** [makocchi-git/actions-k8s-manifests-validate-conftest#1]
Actionを取得できないようです。「Using custom policies in your repository」を利用してます。

Getting action download info
Failed to resolve action download info. Error: Unable to resolve action `makocchi-git/actions-k8s-manifests-validate-conftest@1.1.0`, unable to find version `1.1.0`
Retrying in 19.327 seconds
Failed to resolve action download info. Error: Unable to resolve action `makocchi-git/actions-k8s-manifests-validate-conftest@1.1.0`, unable to find version `1.1.0`
Retrying in 11.277 seconds
Error: Unable to resolve action `makocchi-git/actions-k8s-manifests-validate-conftest@1.1.0`, unable to find version `1.1.0`

**Comment by makocchi-git** [comment]
@cyberblack28 紛らわしくてごめんなさい。こちら `1.1.0` ではなくて v をつけて `v1.1.0` になります

ちなみに、中身の binary を最新にした `v1.2.0` も作っておきましたので、よかったらそちらも試してみてください

**Comment by cyberblack28** [comment]
あっ、なるほど！ありがとうございます。
試してみます。
